### PR TITLE
Translation updates (PR)

### PR DESCRIPTION
**Pull request by cooljeanius**
This PR resolves issue #11

### CODE REVIEW

**Comment by cooljeanius** [comment]
cc @Toranks

**Comment by inferno8** [comment]
Interesting. I thought it was impossible to extract already translated messages from .mo files. Thanks to that msgunfmt trick, new translators will never have to worry about starting from scratch. Nice!

But I am not a fan of uploading all these .po files together with the whole campaign to the add-ons server (additional 6MB of mostly worthless data for gamers). 

Maybe it would be better to completely exclude the .po extension in a _server.ign file...
Then I would inform potential new translators (in translators_readme.txt and on the forums), that if they want to translate, they should download all the necessary .po files directly from this repo.

**Comment by cooljeanius** [comment]
well, Wesnoth can read pofiles directly now, so you could also just as easily get rid of the mofiles instead; any speedup provided by having them compiled is negligible these days...

**Comment by Toranks** [comment]
Excluding po files in server.ign is common practice as far as I know. I have it configured like this too.

**Comment by cooljeanius** [comment]
...it looks like the `_server.ign` isn't even checked into this repo? Does one even exist for this campaign yet?

**Comment by Toranks** [comment]
It is possible that he have excluded that file in git, so even if he have it, it would not be uploaded to github xD

**Comment by inferno8** [comment]
> ...it looks like the `_server.ign` isn't even checked into this repo? Does one even exist for this campaign yet?

Such file currently does not exist for TLU, but the campaign will need it once I merge this PR - I decided to exclude .po files in `_server.ign`. I will commit the file soon.

**Comment by cooljeanius** [comment]
> > ...it looks like the `_server.ign` isn't even checked into this repo? Does one even exist for this campaign yet?
> 
> Such file currently does not exist for TLU, but the campaign will need it once I merge this PR - I decided to exclude .po files in `_server.ign`. I will commit the file soon.

OK, be sure to mention this issue number in your commit message so that it gets cross-referenced here

**Pull request merged**
