### PR TITLE
New AMLAS

### PR DESCRIPTION
**Pull request by Slayer95**
Addresses #32 

More info soon

### CODE REVIEW

**Comment by Slayer95** [comment]
## Mehir AMLAs (bonuses)

|    Type      |                      v3.7                     |      Proposal                                                                                                                   |
|--------------|-----------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------|
| HP           | (a) +5 HP, then (b) +8 HP                     | Unchanged                                                                                                                       |
| Movement     | +1 Movement Point                             | Unchanged                                                                                                                       |
| Sword        | (a) +2 Damage, +1 HP, (b) +1 Strike, +2 HP    | (a), then (b)                                                                                                                   |
| Hammer       | +4 Damage, +1 HP                              | Unchanged                                                                                                                       |
| Magic Raw    | +3 Damage, +3 HP                              | Unchanged                                                                                                                       |
| Magic Special| (NEW)                                         | (a) 1st-strike scroll, then (b) 1st-strike CoD, then (c) slow CoD + melee defense-only CoD                                      |
| Passive XP   | (a) +1 XP/turn                                | (a) +1 XP/turn, then (b) +3 XP/turn (total +4)                                                                                  |
| Summoning    | (NEW)                                         | (a) Movility enabled, then (b) +8 XP for summons                                                                                |
| Gold         | (NEW)                                         | (a) +1 Gold from humans/mechs dead nearby, then (b) +0/1/1/2/2 Gold from foe humans/mechs dead nearby, according to level.      |
| Resistance   | +20% fire/cold/arcane, + circle of resistance | Unchanged                                                                                                                       |
| Spawn gates  | 1 DG II/turn                                  | Unchanged                                                                                                                       |

**Comment by inferno8** [comment]
I approve these changes and additions.
The improvements will definitely make leveling him up more interesting than ever before. I can only hope he won't become far more powerful than Rashti. On the other hand she is immortal, so nothing can beat that.

Let me know when the PR is ready, so I can merge it.

**Comment by Slayer95** [comment]
I got trolled by my ISP, and two more charts remained unsent. Here they are.

## Mehir AMLAs (penalties)

|    Type      |                                                      v3.7                                                 |                           Proposal                                                                                              |
|--------------|-----------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------|
| HP           | (a) +5 HP, then (b) +8 HP                                                                                 | Unchanged                                                                                                                       |
| Movement     | Learned before leader: +10% XP.                                                                           | XP penalty deleted after promotion to Leader                                                                                    |
| Sword        | (a) Learned before leader: +15% XP permanently. (b) Learned before leader: +25% XP. After: +10% XP.       | (a) Penalty lifted after Leader, (b) Penalty down to +10% XP after Leader                                                       |
| Hammer       | (a) Learned before leader: +15% XP permanently.                                                           | XP Penalty lifted after Leader                                                                                                  |
| Magic Raw    | (a) Learned before leader: +15% XP permanently.                                                           | XP Penalty lifted after Leader                                                                                                  |
| Magic Special| (NEW)                                                                                                     | (a) 25%, then 14% after leader, then (b) nothing (*) (c) nothing                                                                    |
| Passive XP   | (a) Learned before leader: +15% XP. (b) (NEW)                                                             | XP Penalty lifted after Leader                                                                                                  |
| Summoning    | (NEW)                                                                                                     | (a) +15% XP before leader, afterwards lifted. (b) +25% XP before leader, penalty dow to +14% XP after leader                    |
| Gold         | (NEW)                                                                                                     | (a) +25% XP before leader, afterwards down to 10%. (b) +25% XP before leader, afterwards down to 14%.                           |
| Resistance   | Kinda superceded by Ultimate Circle                                                                       | Unchanged                                                                                                                       |
| Spawn gates  | +10% XP.                                                                                                  | Unchanged                                                                                                                       |

## Rashti AMLAs

|    Type   |    v3.7    |      Proposal                                                        | 
|-----------|------------|----------------------------------------------------------------------|
| Strength  | (NEW)      | +10% damage with magical scimitar or divine spear                    |
| Magic     | (NEW)      | +10% damage with fire ball, ice ball, light beam, dimensional vortex |
| Intellect | (NEW)      | -30% XP                                                              |
| Sadism    | (NEW)      | +25% damage against enemies who have 40% or less of ther max HP      |
| Majesty   | (NEW)      | -1 strike from enemies' retaliation                                  |
| Summoning | (NEW)      | Movility enabled                                                     |

**Comment by Slayer95** [comment]
I also had a few open questions. I am glad you already approve it as is. But I post them for future reference.

# Open questions
- Whether *taken* HP AMLAs should be upgraded from +5 to +8 each when Mehir becomes TLS.
- Whether the resistance AMLA is fine.
- Whether a gold income AMLA is actually a good idea.
- Whether to disable gold income from Lv0 units.
- Whether Tharis, monsters, destroyers, and/or abyssal beings should also provide income after dying.
- Whether to remove regeneration on circle of destruction AMLA and under which conditions (it ocurred to me
that if Mehir isn't 24/7 using/ready to use its circle (i.e. first strike behavior), then he needn't lose regen.)
- Whether the magic specials line is too strong.
- Whether 8 XP for summons is too much or too little (Fire/Water/Air/Earth level up at 42/29/40/42 XP.)
- Whether an alternative to Spawn Gates is needed for TLS.
- Whether Mehir or Rashti's base combat power should be nerfed in compensation.
- Whether Mehir's max XP should be decreased or increased across all levels in compensation.
- Whether Era of Magic's Veteran AMLA should be available.

**Comment by Slayer95** [comment]
Actually, given that the Ring of Regeneration exists, taking Regeneration away of Mehir would be a coding and playability nightmare. Maybe I should just increase the XP penalties of the Circle of Destruction line? And add an HP penalty? :o

**Comment by inferno8** [comment]
> Actually, given that the Ring of Regeneration exists, taking Regeneration away of Mehir would be a coding and playability nightmare. Maybe I should just increase the XP penalties of the Circle of Destruction line?

Yeah, that seems reasonable.



> * Whether _taken_ HP AMLAs should be upgraded from +5 to +8 each when Mehir becomes TLS.

No, I think +5 is enough. With other AMLAs and TLS he is already a tank.

> * Whether the resistance AMLA is fine.

After reading your previous observations it looks like it introduces some resistance stacking issues. Removing this AMLa completely and making it part of TLS stats by default probably should be enough, but I am not 100% sure.

> * Whether a gold income AMLA is actually a good idea.

It might be hard to balance. If you are unsure, I suggest to test it first and then decide or skip it for now. There are plenty of other AMLAs already.

> * Whether to disable gold income from Lv0 units.
> 
> * Whether Tharis, monsters, destroyers, and/or abyssal beings should also provide income after dying.

If we include the gold AMLA, the income from lv0 units should be disabled. In case of undead and magical beings, I'd disable this.

> * Whether the magic specials line is too strong.

It is safe to assume the magic specials line is too OP, Maybe removing (c) (slow for CoD) should solve some issues here.

> * Whether 8 XP for summons is too much or too little (Fire/Water/Air/Earth level up at 42/29/40/42 XP.)

8 XP looks good to me. I'd leave it unchanged for now or decrease it to 6 XP. This AMLA definitely requires some testing.

> * Whether Mehir or Rashti's base combat power should be nerfed in compensation.
> 
> * Whether Mehir's max XP should be decreased or increased across all levels in compensation.

Instead of nerfing Mehir's combat power I'd probably increase Mehir's max XP so that he doesn't get too many of these AMLAs, because they seem to be really powerful. I'd leave Rashti stats unchanged.

> * Whether Era of Magic's Veteran AMLA should be available.

The Veteran AMLA has been intentionally enabled for EoMa only to improve MP balance. It is still very experimental. I am not planning to enable it for TLU, because it would significantly impact many scenarios and would probably require rebalancing of the entire campaign.

**Comment by Slayer95** [comment]
> No, I think +5 is enough. With other AMLAs and TLS he is already a tank.

Agreed.

> After reading your previous observations it looks like it introduces some resistance stacking issues. Removing this AMLa completely and making it part of TLS stats by default probably should be enough, but I am not 100% sure.

It helps so much in Abyssal Rebellion and other maps, too.

**Comment by Slayer95** [comment]
> No, I think +5 is enough. With other AMLAs and TLS he is already a tank.

Agreed.

> After reading your previous observations it looks like it introduces some resistance stacking issues. Removing this AMLa completely and making it part of TLS stats by default probably should be enough, but I am not 100% sure.

It helps so much in Abyssal Rebellion and other maps, too.

> It might be hard to balance. If you are unsure, I suggest to test it first and then decide or skip it for now. There are plenty of other AMLAs already.

IMO it wouldn't hurt. But I'd rather leave it for later (#35 comes to mind).

> It is safe to assume the magic specials line is too OP, Maybe removing (c) (slow for CoD) should solve some issues here.

TLS already is capable of mass-slowing enemies, so I am not positive that's the best path. But I'd rather err on the safe side and axe it.

> 8 XP looks good to me. I'd leave it unchanged for now or decrease it to 6 XP. This AMLA definitely requires some testing.

Yeah, I am tentatively leaving it at 8 XP.

> Instead of nerfing Mehir's combat power I'd probably increase Mehir's max XP so that he doesn't get too many of these AMLAs, because they seem to be really powerful. I'd leave Rashti stats unchanged.

Alright, I increased its max XP by a bit more than 10%, except for Mehir Guard.

As far as I am concerned, it should be ready to merge.

**Pull request merged**
